# Generated by Django 4.2.12 on 2025-06-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("data", models.JSONField()),
                ("location", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source"], name="data_collec_source_45a315_idx"
                    ),
                    models.Index(
                        fields=["location"], name="data_collec_locatio_9e38dd_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="data_collec_timesta_f48020_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("latitude", "longitude")},
            },
        ),
        migrations.CreateModel(
            name="ProcessedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("location", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_data",
                    models.ManyToManyField(
                        related_name="processed_data", to="data_collection.rawdata"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["location"], name="data_collec_locatio_8f29dd_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="data_collec_timesta_ba78f8_idx"
                    ),
                ],
            },
        ),
    ]
